# Generated by Django 5.1.4 on 2025-01-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('tldr', models.TextField()),
                ('content', models.TextField()),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('html_content', models.TextField(editable=False)),
                ('html_tldr', models.TextField(editable=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag')),
            ],
        ),
    ]
